package dev.dsh.pocket

import java.util.Locale

/**
 * Two-language text table.
 *
 * The Chinese source string is the key, so a literal that was never translated
 * still renders correctly instead of showing a missing-resource placeholder.
 * Chinese is detected from the system locale, which is what "自动识别系统语言"
 * means here; English is the fallback for every other locale.
 *
 * Strings that mix in Kotlin string templates (\$name) or escapes are translated
 * at their call site instead, because the runtime value no longer matches the key.
 */
object Lang {
    val chinese: Boolean get() = Locale.getDefault().language.startsWith("zh")

    private val english: Map<String, String> = mapOf(
        " 项 · " to " items · ",
        " 行" to " lines",
        " 页" to "",
        "（压缩后）" to " (packed)",
        ")}」的消息与工具记录会一并删除，项目文件不受影响。" to ") and its tool log are deleted; project files are untouched.",
        "[已隐藏]" to "[hidden]",
        "○ 等待连接 Termux" to "○ Waiting for Termux",
        "○ 完成首次连接" to "○ Finish the first connection",
        "● 本地已连接 · Termux" to "● Connected · Termux",
        "● Termux 已连接" to "● Termux connected",
        "安装 / 检查 Android 引擎" to "Install / check the Android engine",
        "安装 Node / Python" to "Install Node / Python",
        "把开发环境带在身边" to "Your development environment, in your pocket",
        "保存" to "Save",
        "保存并启用预设" to "Save and activate",
        "保存失败" to "Could not save",
        "本地服务版本落后，将自动更新。更新会结束终端连接，保留工作区和对话记录。" to
            "The local service is out of date and will be updated. Updating ends terminal sessions but keeps workspaces and chats.",
        "本地服务只能使用本机回环地址" to "The local service only accepts loopback addresses",
        "本地环境" to "Local environment",
        "编码" to "Encoding",
        "不支持的 API 协议" to "Unsupported API protocol",
        "操作失败" to "The operation failed",
        "测试会发送一条简短生成请求，可能消耗少量额度。密钥使用 Android Keystore 加密保存；切换连接后请新建会话。" to
            "The test sends one short request and may cost a little credit. The key is encrypted with the Android Keystore; start a new chat after switching.",
        "测试失败" to "Test failed",
        "测试所选模型" to "Test the selected model",
        "查询模型" to "List models",
        "出错" to "Error",
        "创建" to "Create",
        "此目录为空或尚未成功打开。" to "This folder is empty or was not opened successfully.",
        "此文件是 GBK 编码，已按 GBK 正确显示。Node 无法写回 GBK：编辑后保存会将文件转为 UTF-8（中文内容不变，其他程序仍可读）。" to
            "This file is GBK-encoded and is shown correctly as GBK. Node cannot write GBK back, so saving an edit converts it to UTF-8 (Chinese text is unchanged and other programs can still read it).",
        "从列表移除" to "Remove from list",
        "从列表移除工作区？" to "Remove this workspace?",
        "从想法，到运行" to "From an idea to running code",
        "从一个文件夹开始" to "Start from a folder",
        "打开方式" to "Open with",
        "打开路径" to "Open path",
        "打开原生 Termux 终端" to "Open the native Termux terminal",
        "打开终端" to "Open terminal",
        "打开终端失败" to "Could not open the terminal",
        "大小" to "Size",
        "单次输出上限" to "Max output per reply",
        "点右上角「更多」→「用其他应用打开」" to "Tap ⋯ above, then “Open with another app”",
        "端点未提供模型列表；可手动填写模型 ID 后测试" to "The endpoint listed no models; type a model id and test it",
        "端口 8765 无监听，Termux 服务未运行" to "Nothing is listening on port 8765; the Termux service is not running",
        "对话" to "Chats",
        "对话操作" to "Chat actions",
        "发送" to "Send",
        "返回" to "Back",
        "放大" to "Zoom in",
        "放弃改动" to "Discard changes",
        "复制配置并打开 Termux" to "Copy the setup command and open Termux",
        "复制全文" to "Copy all text",
        "更多" to "More",
        "更新本地服务" to "Update the local service",
        "工具与运行活动" to "Tool and run activity",
        "这条对话的消息和工具记录会一并删除，项目文件不受影响。" to "The messages and tool log of this chat are deleted together; project files are untouched.",
        "只会移除这条记录，磁盘上的项目文件不会被删除。" to "Only this record is removed; the project files on disk are not deleted.",
        "工作区" to "Workspaces",
        "工作区操作" to "Workspace actions",
        "工作区与会话" to "Workspaces and chats",
        "关闭" to "Close",
        "环境" to "Setup",
        "继续编辑" to "Keep editing",
        "结束终端" to "End terminal",
        "今天想做些什么？" to "What would you like to do?",
        "仅填域名时补 /v1" to "A bare domain gets /v1 appended",
        "进入项目目录，运行熟悉的命令。" to "Work in your project folder with the commands you already know.",
        "开发版先使用 DSH 的 sdk-minimal 配置，提供持久 Shell 和会话。模型可通过 Shell 读写代码、运行工具。" to
            "The preview uses the DSH sdk-minimal profile, which provides a persistent shell and sessions. The model can read and write code and run tools through that shell.",
        "可保存多个端点和密钥；选择协议后自动配置 DSH 适配器。" to
            "Keep several endpoints and keys; picking a protocol configures the DSH adapter automatically.",
        "可选择 SD 卡 / USB 硬盘目录。权限由 Termux 决定；若盘根目录不可写，可尝试 ~/storage/external-1。" to
            "You can pick a folder on an SD card or USB drive. Access is decided by Termux; if the drive root is not writable, try ~/storage/external-1.",
        "类型" to "Type",
        "离开会丢弃这次编辑。" to "Leaving discards this edit.",
        "连接本机 Termux，在真实项目中对话、修改文件和运行命令。" to
            "Connect to Termux on this device and chat, edit files and run commands in real projects.",
        "连接超时，Termux 可能已被系统杀死" to "Connection timed out; the system may have killed Termux",
        "连接或刷新" to "Connect or refresh",
        "连接与模型设置" to "Connection and model settings",
        "浏览真实文件，查看代码。" to "Browse real files and read code.",
        "路径" to "Path",
        "密钥" to "Key",
        "描述你想完成的任务…" to "Describe the task you want done…",
        "描述任务，DSH 会在当前项目里工作。" to "Describe a task and DSH works inside the current project.",
        "明文 HTTP 被系统策略拦截" to "Plain HTTP was blocked by system policy",
        "模型 ID（可手动填写）" to "Model id (you can type it)",
        "模型列表为空，可手动填写模型 ID 后测试" to "The model list is empty; type a model id to test",
        "目录路径（支持 ~/）" to "Folder path (~/ is supported)",
        "内部存储" to "Internal storage",
        "你" to "You",
        "你的完整终端" to "Your full terminal",
        "你的移动开发空间" to "Your mobile development space",
        "配对密钥不匹配" to "The pairing key does not match",
        "配置本地环境" to "Set up the local environment",
        "启动本地服务" to "Start the local service",
        "请到 设置 → WLAN → 当前网络 → 高级 → 代理 改为「无」，或重启手机后再试。" to
            "Set Settings → WLAN → current network → Advanced → Proxy to “None”, or reboot and try again.",
        "请到 设置 → WLAN → 当前网络 → 高级 → 代理，改为「无」。" to
            "Set Settings → WLAN → current network → Advanced → Proxy to “None”.",
        "请检查地址、协议和密钥" to "Check the address, protocol and key",
        "请求被代理接管（收到 HTML 而非本地服务的 JSON）" to "A proxy took the request (HTML instead of the local service JSON)",
        "请填写或选择模型 ID" to "Enter or pick a model id",
        "请填写预设名称和模型 ID" to "Enter a preset name and a model id",
        "请先输入 API Key" to "Enter an API key first",
        "请在系统设置 → DSH Pocket → 权限中允许在 Termux 运行命令" to
            "Allow DSH Pocket to run commands in Termux under Settings → DSH Pocket → Permissions",
        "请至少保留一个预设" to "Keep at least one preset",
        "取消" to "Cancel",
        "取消星标" to "Unstar",
        "任务已停止，记录已保存。继续提问会在同一目录重新启动 DSH。" to
            "The task stopped and the log is saved. Asking again restarts DSH in the same folder.",
        "仍然覆盖" to "Overwrite anyway",
        "若 Termux 显示 local service already running，说明服务在跑但 App 连不上；" to
            "If Termux says the local service is already running, the service is up but the app cannot reach it; ",
        "删除" to "Delete",
        "删除此连接的已保存端点和密钥。" to "Delete the saved endpoint and key for this connection.",
        "删除此预设" to "Delete this preset",
        "删除对话" to "Delete chat",
        "删除预设？" to "Delete this preset?",
        "删除这个对话？" to "Delete this chat?",
        "上次运行出错。继续提问会重启 DSH。" to "The last run failed. Asking again restarts DSH.",
        "上次运行的对话。继续提问会接上这段记录并重新启动 DSH。" to "A chat from a previous run. Asking again resumes that history and restarts DSH.",
        "十六进制" to "Hex",
        "思考" to "Thinking",
        "收起" to "Collapse",
        "展开" to "Expand",
        "已读取文件" to "read files",
        "已写入文件" to "wrote files",
        "运行了代码" to "ran code",
        "已搜索文件" to "searched files",
        "执行了工具" to "used tools",
        "、" to ", ",
        "并" to " and ",
        " 步" to " steps",
        "读取 " to "Read ",
        "写入 " to "Write ",
        "运行 " to "Run ",
        "搜索 " to "Search ",
        "显示前 " to "first ",
        "（文件更大，仅显示开头）" to " (the file is larger; only the start is shown)",
        "查找" to "Find",
        "查找文本" to "Find text",
        "上一个" to "Previous",
        "下一个" to "Next",
        "解压到此处" to "Extract here",
        "解压失败" to "Extraction failed",
        "已解压 " to "Extracted ",
        " 个文件到 " to " files to ",
        "上下文长度" to "Context window",
        "上一级" to "Up one level",
        "尚未保存" to "Not saved yet",
        "尚未尝试连接" to "No connection attempt yet",
        "尚未检测到引擎" to "No engine detected yet",
        "使用此目录" to "Use this folder",
        "授权 Termux 存储" to "Grant Termux storage access",
        "授予权限" to "Grant permission",
        "刷新存储" to "Refresh storage",
        "刷新文件" to "Refresh files",
        "刷新状态" to "Refresh status",
        "说明" to "Note",
        "缩小" to "Zoom out",
        "添加工作区" to "Add a workspace",
        "条目过多，仅显示前一部分。" to "Too many entries; only the first part is shown.",
        "停止任务" to "Stop the task",
        "通常是系统代理 / Wi-Fi 手动代理接管了 127.0.0.1:8765；" to
            "A system or Wi-Fi proxy usually captured 127.0.0.1:8765; ",
        "外接盘无法写入？打开 Termux 权限设置" to "Cannot write to the drive? Open Termux permission settings",
        "未选择工作区" to "No workspace selected",
        "文件" to "Files",
        "文件夹" to "Folder",
        "文件夹名称" to "Folder name",
        "文件内容" to "File contents",
        "文件信息" to "File info",
        "文件已被外部修改" to "The file changed elsewhere",
        "无法打开" to "Cannot open",
        "无法打开权限设置" to "Cannot open the permission settings",
        "无法读取这个压缩包" to "Cannot read this archive",
        "无法解析这个 PDF（可能已加密）" to "Cannot parse this PDF (it may be encrypted)",
        "下载失败 (HTTP " to "Download failed (HTTP ",
        "响应内容为空" to "The response was empty",
        "项目文件" to "Project files",
        "新建对话" to "New chat",
        "新建会话" to "New chat",
        "新建文件夹" to "New folder",
        "新增预设" to "Add preset",
        "星标置顶" to "Star to pin",
        "修改时间" to "Modified",
        "选择工作区" to "Choose a workspace",
        "选择工作区目录" to "Choose a workspace folder",
        "选择已有项目，或创建一个新的目录。文件保留在原位置。" to
            "Pick an existing project or create a new folder. Files stay where they are.",
        "验证读写" to "Verify read/write",
        "验证失败" to "Verification failed",
        "验证中…" to "Verifying…",
        "移除" to "Remove",
        "已保存" to "Saved",
        "已保存并启用；请在新会话中使用。" to "Saved and activated; use it in a new chat.",
        "已被外部修改" to "changed elsewhere",
        "已发现 DSH · SDK 模式" to "DSH found · SDK mode",
        "用其他应用打开" to "Open with another app",
        "语言" to "Language",
        "预设名称" to "Preset name",
        "原有连接" to "Existing connection",
        "允许此会话在 Termux 权限范围内修改文件、执行命令" to
            "Let this chat edit files and run commands within Termux permissions",
        "运行中" to "Running",
        "在此项目新建对话" to "New chat in this project",
        "在此新建文件夹" to "New folder here",
        "在终端打开" to "Open in terminal",
        "在终端运行" to "Run in terminal",
        "这个 PDF 没有可显示的页面" to "This PDF has no displayable pages",
        "这个格式不能在内置查看器里显示。" to "This format cannot be shown in the built-in viewer.",
        "这个文件在别处（很可能是终端里的 DSH）被改过。覆盖会丢弃那些改动。" to
            "This file changed elsewhere, most likely from DSH in the terminal. Overwriting discards those changes.",
        "这是上次运行留下的记录，只读。" to "This is a record from the previous run; read-only.",
        "诊断 App 侧（网络原始信息）" to "Diagnose the app side (raw network view)",
        "诊断 Termux 侧" to "Diagnose the Termux side",
        "正在查询模型…" to "Listing models…",
        "正在发送简短测试请求…" to "Sending a short test request…",
        "正在连接…" to "Connecting…",
        "正在验证…" to "Verifying…",
        "只读查看" to "View read-only",
        "终端" to "Terminal",
        "终端连接已断开" to "The terminal disconnected",
        "终端输入失败" to "Terminal input failed",
        "重新打开" to "Reopen",
        "主目录" to "Home",
        "转为 UTF-8 编辑" to "Convert to UTF-8 and edit",
        "最近对话" to "Recent chats",
        "API 地址不能包含账号、查询参数或片段" to "The API address cannot contain credentials, a query or a fragment",
        "API 端点 / 基础地址" to "API endpoint / base URL",
        "API 返回的不是 JSON，请检查端点路径" to "The API did not return JSON; check the endpoint path",
        "API 返回空响应" to "The API returned an empty response",
        "API 连接预设" to "API connection presets",
        "API 响应过大" to "The API response is too large",
        "DSH 和命令运行在手机上的完整 Termux 中。" to "DSH and your commands run in the full Termux on this device.",
        "DSH 引擎" to "DSH engine",
        "DSH 正在工作…" to "DSH is working…",
        "DSH Pocket · 独立开发项目，与 DeepSeek 官方应用无隶属关系。" to
            "DSH Pocket · an independent project, not affiliated with the official DeepSeek app.",
        "GBK 编码" to "GBK encoding",
        "HTTP 请求成功，但响应不符合所选协议" to "The HTTP request succeeded but the response does not match the chosen protocol",
        "OpenAI Chat Completions（常用）" to "OpenAI Chat Completions (common)",
        "Termux 配置" to "Termux setup",
        "Termux 暂时无法访问，请授权或重新连接存储后刷新。" to
            "Termux cannot reach this right now; grant storage access or reconnect and refresh.",
        // Fragments used around a Kotlin string template; the template itself
        // cannot be a lookup key because the runtime value has the interpolation.
        "开发预览" to "preview",
        "查看工具活动 · " to "View tool activity · ",
        "（不可访问）" to " (unavailable)",
        "读写验证通过：" to "Read/write check passed: ",
        "连接地址：" to "Address: ",
        "切换预设 · " to "Switch preset · ",
        "协议 · " to "Protocol · ",
        "实际请求：" to "Actual request: ",
        "地址无效：" to "Invalid address: ",
        "选择查询到的模型 · " to "Pick a discovered model · ",
        " 个" to "",
        "部分旧输出已滚出缓存；可按 Ctrl+L 重绘" to "Some older output scrolled out of the buffer; press Ctrl+L to redraw",
        "终端已退出" to "The terminal exited",
        "发现 " to "Found ",
        " 个模型。列表不代表每个模型均可调用，请选择后测试。" to " models. The list does not mean every model is callable; pick one and test it.",
        "查询失败: " to "Lookup failed: ",
        "系统默认代理: " to "System proxy: ",
        "(未设置)" to "(not set)",
        "密钥长度: " to "Key length: ",
        "异常 " to "Error ",
        "响应不是有效 JSON（HTTP " to "Response is not valid JSON (HTTP ",
        "）: " to "): ",
        "连接失败 (" to "Connection failed (",
        "本应用强制: " to "App forces: ",
        "  (即永远直连)" to "  (always direct)",
        "收到 HTML 而非 JSON（HTTP " to "Received HTML instead of JSON (HTTP ",
        "），请求未到达本地服务。" to "); the request never reached the local service.",
        "API 返回错误：" to "API error: ",
        "模型 " to "Model ",
        " 请求成功。工具调用能力会在 DSH 对话中进一步验证。" to " responded. Tool calling is verified further inside a DSH chat.",
        "请先安装并打开 Termux" to "Install Termux and open it first",
        "请先授予“在 Termux 环境中运行命令”权限" to "Grant the permission to run commands in Termux first",
        "已发送：" to "Sent to Termux: ",
        "。前台任务的进度会显示在 Termux 中。" to ". Foreground progress is shown in Termux.",
        "Termux 没有响应" to "Termux did not respond",
        "DSH Pocket 本地服务" to "DSH Pocket local service",
        "更新 DSH Pocket 本地服务" to "Update the DSH Pocket local service",
        "安装 DSH Android 引擎" to "Install the DSH Android engine",
        "安装本地运行环境" to "Install the local runtime",
        "授权访问手机共享存储" to "Grant access to shared storage",
        "诊断本地服务连接" to "Diagnose the local service connection",
        "项目终端" to "Project terminal",
        "尚未安装 Termux" to "Termux is not installed",
        "未知" to "Unknown",
        "Termux 任务结束 · 退出码 " to "Termux task finished · exit code ",
        "请在 Termux 执行: pkg install nodejs-lts python" to "Run in Termux: pkg install nodejs-lts python",
        "1. 允许本应用在 Termux 中运行命令。\n2. 复制配置命令，在 Termux 中执行一次。\n3. 安装基础环境，然后启动服务。" to
            "1. Let this app run commands in Termux.\n2. Copy the setup command and run it in Termux once.\n3. Install the runtime, then start the service.",
        "本地服务无响应（" to "The local service did not respond (",
        "；已尝试 " to "; tried ",
        "）。" to ").",
        "若 Termux 显示 local service already running，说明服务在跑但 App 连不上；请到 设置 → WLAN → 当前网络 → 高级 → 代理 改为「无」，或重启手机后再试。" to
            "If Termux reports the local service already running, the service is up but the app cannot reach it. Set Settings → WLAN → current network → Advanced → Proxy to “None”, or reboot and try again.",
    )

    fun tr(text: String): String = if (chinese) text else english[text] ?: text
}

/** Shorthand so call sites stay readable. */
fun tr(text: String): String = Lang.tr(text)
